# Generated by Django 5.2.12 on 2026-04-03 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeIngestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='resumes/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('review_pending', 'Review Pending')], db_index=True, default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume_ingestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resume_ingestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeParsedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('llm_output', models.JSONField(default=dict)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('parser_version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='resumes.resumeingestion')),
            ],
            options={
                'db_table': 'resume_parsed_data',
            },
        ),
        migrations.AddIndex(
            model_name='resumeingestion',
            index=models.Index(fields=['status', 'created_at'], name='idx_ingestion_status_date'),
        ),
        migrations.AddIndex(
            model_name='resumeingestion',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='idx_ingestion_user_date'),
        ),
    ]
