# Generated by Django 6.0.3 on 2026-04-01 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('competencies', models.JSONField(default=list, help_text='List of competency objects: [{"name": "...", "description": "..."}]')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_feedback_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveSmallIntegerField(help_text='1 = Round 1, 2 = Round 2, etc.')),
                ('round_label', models.CharField(help_text='Display label, e.g., "Round 1 - Tech", "Final"', max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('mode', models.CharField(choices=[('virtual', 'Virtual'), ('phone', 'Phone Call'), ('face_to_face', 'Face-to-Face')], default='virtual', max_length=15)),
                ('meeting_link', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
                ('feedback_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='interviews.feedbacktemplate')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_interviews', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.candidatejobmapping')),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.PositiveSmallIntegerField(help_text='Rating 1-5')),
                ('recommendation', models.CharField(choices=[('proceed', 'Proceed'), ('hold', 'Hold'), ('reject', 'Reject')], max_length=10)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interviews.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_feedback',
            },
        ),
        migrations.CreateModel(
            name='CompetencyRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competency_name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating 1-5')),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='interviews.interviewfeedback')),
            ],
            options={
                'db_table': 'competency_ratings',
            },
        ),
        migrations.AddConstraint(
            model_name='interview',
            constraint=models.UniqueConstraint(fields=('mapping', 'round_number'), name='unique_interview_round_per_mapping'),
        ),
    ]
