# Generated by Django 5.2.12 on 2026-04-01 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_remove_candidatejobmapping_unique_candidate_per_job_and_more'),
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacktemplate',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='interview',
            name='unique_interview_round_per_mapping',
        ),
        migrations.RemoveField(
            model_name='feedbacktemplate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='competencyrating',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='competencies',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='feedback_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.feedbacktemplate'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='round_label',
            field=models.CharField(default='Round 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='interview',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=15),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='interview',
            constraint=models.UniqueConstraint(fields=('mapping', 'round_number'), name='unique_interview_round'),
        ),
        migrations.AlterModelTable(
            name='competencyrating',
            table=None,
        ),
        migrations.AlterModelTable(
            name='feedbacktemplate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='interview',
            table=None,
        ),
        migrations.AlterModelTable(
            name='interviewfeedback',
            table=None,
        ),
    ]
