# Generated by Django 5.2.12 on 2026-04-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_remove_unique_interview_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='concerns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='decision',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('ON_HOLD', 'On Hold')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
