# Generated by Django 6.0.3 on 2026-04-01 08:51

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('current_employer', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('current_ctc_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expected_ctc_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notice_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Upload'), ('bulk', 'Bulk Excel Upload'), ('quick', 'Quick Upload')], default='manual', max_length=10)),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Full structured extraction from Claude API')),
                ('parsing_status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='skipped', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateJobMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('on_hold', 'On Hold'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('offered', 'Offered'), ('joined', 'Joined')], db_index=True, default='pending', max_length=15)),
                ('stage_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_mappings', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_mappings', to='jobs.job')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_moves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_job_mappings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='candidates.candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(blank=True, max_length=15)),
                ('to_stage', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_changes', to=settings.AUTH_USER_MODEL)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='candidates.candidatejobmapping')),
            ],
            options={
                'db_table': 'pipeline_stage_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='resumes/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=4)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('raw_text', models.TextField(blank=True, help_text='Extracted text from resume (before AI parsing)')),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_files', to='candidates.candidate')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resume_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['full_name'], name='idx_candidate_name'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['parsing_status'], name='idx_candidate_parse_status'),
        ),
        migrations.AddIndex(
            model_name='candidatejobmapping',
            index=models.Index(fields=['job', 'stage'], name='idx_mapping_job_stage'),
        ),
        migrations.AddConstraint(
            model_name='candidatejobmapping',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_per_job'),
        ),
    ]
