# Generated by Django 5.2.12 on 2026-04-09 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0003_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('recruiter_upload', 'Recruiter Upload'), ('naukri', 'Naukri'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatejobmapping',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('on_hold', 'On Hold'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('offered', 'Offered'), ('joined', 'Joined')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='candidatejobmapping',
            index=models.Index(fields=['job', 'stage'], name='cjm_job_stage_idx'),
        ),
    ]
