# Generated by Django 5.2.12 on 2026-04-01 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidatejobmapping',
            name='unique_candidate_per_job',
        ),
        migrations.RemoveIndex(
            model_name='candidate',
            name='idx_candidate_name',
        ),
        migrations.RemoveIndex(
            model_name='candidate',
            name='idx_candidate_parse_status',
        ),
        migrations.RemoveIndex(
            model_name='candidatejobmapping',
            name='idx_mapping_job_stage',
        ),
        migrations.AddField(
            model_name='candidate',
            name='sub_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('recruiter_upload', 'Recruiter Upload'), ('naukri', 'Naukri'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatejobmapping',
            name='moved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidatejobmapping',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('on_hold', 'On Hold'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('offered', 'Offered'), ('joined', 'Joined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatenote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pipelinestagelog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pipelinestagelog',
            name='from_stage',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pipelinestagelog',
            name='to_stage',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='candidatejobmapping',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job'),
        ),
        migrations.AlterModelTable(
            name='candidate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='candidatejobmapping',
            table=None,
        ),
        migrations.AlterModelTable(
            name='candidatenote',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pipelinestagelog',
            table=None,
        ),
    ]
