# Generated by Django 5.2.12 on 2026-04-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_perf_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumefile',
            name='file',
            field=models.FileField(upload_to='ats/resumes/'),
        ),
    ]
