# Generated by Django 5.2.12 on 2026-04-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_resumefile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='expected_ctc_lakhs',
        ),
    ]
