# Generated by Django 5.2.12 on 2026-04-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_pipeline_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatejobmapping',
            name='screening_status',
            field=models.CharField(blank=True, choices=[('SCREENED', 'Screened'), ('MAYBE', 'Maybe'), ('REJECTED', 'Rejected')], default=None, max_length=20, null=True),
        ),
    ]
