# Generated by Django 5.2.12 on 2026-04-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_screening_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatejobmapping',
            name='screening_status',
            field=models.CharField(blank=True, choices=[('SCREENED', 'Screened'), ('MAYBE', 'Maybe'), ('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
    ]
