# Generated by Django 5.2.12 on 2026-04-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_screening_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatejobmapping',
            name='interview_status',
            field=models.CharField(blank=True, choices=[('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidatejobmapping',
            name='current_interview_round',
            field=models.CharField(blank=True, choices=[('R1', 'Round 1'), ('R2', 'Round 2'), ('R3', 'Round 3'), ('CLIENT', 'Client Round'), ('CDO', 'CDO Round'), ('MGMT', 'Management Round')], max_length=10, null=True),
        ),
    ]
