# Generated by Django 5.2.12 on 2026-04-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_clear_education_hr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatereminder',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='candidates.candidatejobmapping'),
        ),
    ]
