# Generated by Django 5.2.12 on 2026-04-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_reminder_job_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatejobmapping',
            name='ai_match_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatejobmapping',
            name='ai_match_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidatejobmapping',
            name='ai_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
