# Generated by Django 5.2.12 on 2026-04-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_add_action_reason'),
        ('candidates', '0013_ai_match_score'),
    ]

    operations = [
    ]
