# Generated by Django 5.2.12 on 2026-04-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of uploaded bytes for duplicate detection', max_length=64),
        ),
    ]
