# Generated by Django 5.2.12 on 2026-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hiring_manager', 'Hiring Manager'), ('recruiter', 'Recruiter'), ('interviewer', 'Interviewer')], default='recruiter', max_length=20),
        ),
    ]
