# Generated by Django 5.2.12 on 2026-04-06 07:19

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('skills_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('job_description', models.TextField(blank=True)),
                ('experience_min', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('experience_max', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('open', 'Open'), ('hidden', 'Hidden'), ('closed', 'Closed')], default='open', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('positions_filled', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('hiring_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='requisitions.requisition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborator_additions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'user'), name='unique_job_collaborator')],
            },
        ),
    ]
