# Generated by Django 6.0.3 on 2026-04-01 08:51

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_code', models.CharField(help_text='Auto-generated: JOB-2026-0001', max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('skills_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('job_description', models.TextField()),
                ('experience_min', models.DecimalField(decimal_places=1, max_digits=4)),
                ('experience_max', models.DecimalField(decimal_places=1, max_digits=4)),
                ('positions_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('hidden', 'Hidden'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('positions_filled', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='departments.department')),
                ('hiring_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_jobs', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='requisitions.requisition')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborator_additions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_collaborators',
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'department'], name='idx_job_status_dept'),
        ),
        migrations.AddConstraint(
            model_name='jobcollaborator',
            constraint=models.UniqueConstraint(fields=('job', 'user'), name='unique_job_collaborator'),
        ),
    ]
