# Generated by Django 5.2.12 on 2026-04-01 11:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='idx_job_status_dept',
        ),
        migrations.RemoveField(
            model_name='job',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='job',
            name='positions_count',
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_max',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('hidden', 'Hidden'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jobcollaborator',
            table=None,
        ),
    ]
