# Generated by Django 5.2.12 on 2026-04-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('hidden', 'Hidden'), ('closed', 'Closed')], db_index=True, default='open', max_length=10),
        ),
    ]
