# Generated by Django 5.2.12 on 2026-04-15 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('abandoned', 'Abandoned'), ('closed', 'Closed')], db_index=True, default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('job_created', 'Job Created'), ('status_changed', 'Status Changed'), ('collaborator_added', 'Collaborator Added'), ('collaborator_removed', 'Collaborator Removed'), ('tat_updated', 'TAT Updated'), ('budget_updated', 'Budget Updated'), ('department_changed', 'Department Changed'), ('hiring_manager_changed', 'Hiring Manager Changed'), ('jd_updated', 'JD Updated'), ('title_updated', 'Title Updated')], max_length=30)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
