# Generated by Django 5.2.12 on 2026-04-15 06:35

from django.db import migrations


def migrate_hidden_to_abandoned(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    Job.objects.filter(status='hidden').update(status='abandoned')


def reverse_abandoned_to_hidden(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    Job.objects.filter(status='abandoned').update(status='hidden')


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_abandoned_history'),
    ]

    operations = [
        migrations.RunPython(migrate_hidden_to_abandoned, reverse_abandoned_to_hidden),
    ]
