# Generated by Django 5.2.12 on 2026-04-06 07:19

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('internship', 'Internship')], default='permanent', max_length=15)),
                ('requisition_type', models.CharField(choices=[('new', 'New'), ('backfill', 'Backfill')], default='new', max_length=10)),
                ('positions_count', models.PositiveIntegerField(default=1)),
                ('experience_min', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('experience_max', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('ctc_currency', models.CharField(default='INR', max_length=10)),
                ('ctc_min_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ctc_max_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('job_description', models.TextField(blank=True)),
                ('roles_responsibilities', models.TextField(blank=True)),
                ('skills_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('skills_desirable', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('skills_to_evaluate', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('min_qualification', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('iit_grad', models.BooleanField(default=False)),
                ('nit_grad', models.BooleanField(default=False)),
                ('iim_grad', models.BooleanField(default=False)),
                ('top_institute', models.BooleanField(default=False)),
                ('female_diversity', models.BooleanField(default=False)),
                ('unicorn_exp', models.BooleanField(default=False)),
                ('top_internet_product', models.BooleanField(default=False)),
                ('top_software_product', models.BooleanField(default=False)),
                ('top_it_services_mnc', models.BooleanField(default=False)),
                ('top_consulting_mnc', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requisitions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('hiring_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hm_requisitions', to=settings.AUTH_USER_MODEL)),
                ('l1_approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requisitions', to=settings.AUTH_USER_MODEL)),
                ('sub_vertical_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_sv1', to='departments.subvertical')),
                ('sub_vertical_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_sv2', to='departments.subvertical')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=15)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='requisitions.requisition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
