# Generated by Django 6.0.3 on 2026-04-01 08:51

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('internship', 'Internship')], default='permanent', max_length=15)),
                ('requisition_type', models.CharField(choices=[('new', 'New'), ('backfill', 'Backfill')], default='new', max_length=10)),
                ('positions_count', models.PositiveIntegerField(default=1)),
                ('experience_min', models.DecimalField(decimal_places=1, max_digits=4)),
                ('experience_max', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ctc_min_lakhs', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum CTC in INR Lakhs', max_digits=8, null=True)),
                ('ctc_max_lakhs', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum CTC in INR Lakhs', max_digits=8, null=True)),
                ('job_description', models.TextField(help_text='Rich-text job description (can be AI-generated)')),
                ('roles_responsibilities', models.TextField(help_text='Rich-text roles & responsibilities (can be AI-generated)')),
                ('skills_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text='Mandatory skills (multi-tag)')),
                ('skills_desirable', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Nice-to-have skills (multi-tag)')),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('min_qualification', models.CharField(blank=True, max_length=100)),
                ('diversity_preference', models.BooleanField(default=False)),
                ('institute_preference', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Preferred institutes (multi-select)')),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Recruiter who created this requisition', on_delete=django.db.models.deletion.PROTECT, related_name='created_requisitions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='departments.department')),
                ('hiring_manager', models.ForeignKey(help_text='Hiring Manager for this role', on_delete=django.db.models.deletion.PROTECT, related_name='hm_requisitions', to=settings.AUTH_USER_MODEL)),
                ('l1_approver', models.ForeignKey(help_text='L1 Approver (receives approval request)', on_delete=django.db.models.deletion.PROTECT, related_name='approval_requisitions', to=settings.AUTH_USER_MODEL)),
                ('sub_vertical_1', models.ForeignKey(blank=True, help_text='Primary sub-vertical', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_sv1', to='departments.subvertical')),
                ('sub_vertical_2', models.ForeignKey(blank=True, help_text='Secondary sub-vertical', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_sv2', to='departments.subvertical')),
            ],
            options={
                'db_table': 'requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='requisitions.requisition')),
            ],
            options={
                'db_table': 'requisition_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['status', 'department'], name='idx_req_status_dept'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['created_by'], name='idx_req_created_by'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['hiring_manager'], name='idx_req_hiring_mgr'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['l1_approver', 'status'], name='idx_req_approver_status'),
        ),
    ]
