# Generated by Django 5.2.12 on 2026-04-01 11:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='requisition',
            name='idx_req_status_dept',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='idx_req_created_by',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='idx_req_hiring_mgr',
        ),
        migrations.RemoveIndex(
            model_name='requisition',
            name='idx_req_approver_status',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='diversity_preference',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='institute_preference',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='sub_vertical_1',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='sub_vertical_2',
        ),
        migrations.AddField(
            model_name='requisition',
            name='sub_vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.subvertical'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='ctc_max_lakhs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='ctc_min_lakhs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='experience_max',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='experience_min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='hiring_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hm_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='l1_approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='roles_responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='skills_desirable',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='skills_required',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisitionapproval',
            name='acted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisitionapproval',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=15),
        ),
        migrations.AlterField(
            model_name='requisitionapproval',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='requisitions.requisition'),
        ),
        migrations.AlterModelTable(
            name='requisition',
            table=None,
        ),
        migrations.AlterModelTable(
            name='requisitionapproval',
            table=None,
        ),
    ]
