# Generated by Django 5.2.12 on 2026-04-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Allocated budget in INR Lakhs', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='tat_days',
            field=models.PositiveIntegerField(blank=True, help_text='Target Turn Around Time in calendar days', null=True),
        ),
    ]
