# Generated by Django 5.2.12 on 2026-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='purpose',
            field=models.CharField(choices=[('internal', 'Internal'), ('client', 'Client')], default='internal', max_length=10),
        ),
    ]
