# Generated by Django 5.2.12 on 2026-04-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_tat_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='ctc_currency',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='ctc_max_lakhs',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='ctc_min_lakhs',
        ),
        migrations.AlterField(
            model_name='requisition',
            name='location',
            field=models.CharField(choices=[('Gurgaon', 'Gurgaon'), ('Noida', 'Noida'), ('Remote', 'Remote')], max_length=50),
        ),
    ]
