# Generated by Django 5.2.12 on 2026-04-02 08:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_subvertical_parent'),
        ('requisitions', '0002_remove_requisition_idx_req_status_dept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='sub_vertical',
        ),
        migrations.AddField(
            model_name='requisition',
            name='ctc_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='requisition',
            name='female_diversity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='iim_grad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='iit_grad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='nit_grad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requisition',
            name='skills_to_evaluate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='requisition',
            name='sub_vertical_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_sv1', to='departments.subvertical'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='sub_vertical_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_sv2', to='departments.subvertical'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='requisition',
            name='top_consulting_mnc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='top_institute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='top_internet_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='top_it_services_mnc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='top_software_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='unicorn_exp',
            field=models.BooleanField(default=False),
        ),
    ]
