# Generated by Django 5.2.12 on 2026-04-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_requisition_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='purpose_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
