# Generated by Django 5.2.12 on 2026-04-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0003_remove_ctc_location_choices'),
        ('requisitions', '0003_requisition_purpose_code'),
    ]

    operations = [
    ]
