# Generated by Django 5.2.12 on 2026-04-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0004_merge_20260416_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('remote', 'Remote'), ('office', 'Office')], default='', max_length=10),
        ),
    ]
