# Generated by Django 5.2.12 on 2026-04-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0005_requisition_salary_max_requisition_salary_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='budget',
        ),
        migrations.AddField(
            model_name='requisition',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget in INR Lakhs', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget in INR Lakhs', max_digits=12, null=True),
        ),
    ]
