# Generated by Django 5.2.12 on 2026-04-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0006_budget_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='roles_responsibilities',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='skills_to_evaluate',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='tags',
        ),
    ]
