# Generated by Django 5.2.12 on 2026-04-24 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0007_remove_unused_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='l1_approver',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='salary_min',
        ),
        migrations.AlterField(
            model_name='requisition',
            name='hiring_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hm_requisitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
