# Generated by Django 5.2.12 on 2026-04-30 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('entity_type', models.CharField(choices=[('candidate', 'Candidate'), ('job', 'Job'), ('interview', 'Interview')], max_length=20)),
                ('entity_id', models.CharField(max_length=64)),
                ('sentence', models.CharField(max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_ac_created_d34040_idx'), models.Index(fields=['actor'], name='activity_ac_actor_i_29e3da_idx'), models.Index(fields=['action'], name='activity_ac_action_0385c4_idx'), models.Index(fields=['entity_type'], name='activity_ac_entity__31458d_idx')],
            },
        ),
    ]
